language: node_js

node_js:
  - "12"
os:
  - linux
dist: 
  - "xenial"
addons:
  sonarcloud:
    organization: "armorjs"
    token:
      secure: "aaaa"
install:
  - yarn install

script:
  - yarn test && yarn build && sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
